language: python
python:
    - 2.7
    - 3.2
    - 3.4

install:
    - pip install coveralls
    - pip install -e .
before_script:
    - cd tests
    - mkdir logs
script:
    - coverage run --source=../mtpdevice runner.py
after_success:
    - coveralls
